[package]
name = "json_path"
version = "0.1.0"
authors = ["parlir <ralph@commure.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
pest = "^1.0"
pest_derive = "^1.0"
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2"